version: '3.8'

services:
  api:
    build: .
    container_name: expense_flow_api
    ports:
      - "8000:8000"
    volumes:
      - ./.data:/app/.data
      - /mnt/sdcard:/mnt/sdcard
    env_file:
      - ./.env
    restart: unless-stopped
    networks:
      - expense_flow_network

networks:
  expense_flow_network:
    driver: bridge